#!/bin/bash
read foo
echo $foo | jq . > /tmp/json2ts_tmp && \
  cat /tmp/json2ts_tmp_i && \
  make_types -i /tmp/json2ts_tmp_i /tmp/json2ts_tmp root && \
  cat /tmp/json2ts_tmp_i && \
  echo "" > /tmp/json2ts_tmp_i

